name: Push to Zips to firebase (dev cuba)

on:
  push:
    branches:
      - dev

jobs:
  build:
    name: Push zips to firebase zips
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Install Firebase CLI
        run: npm install -g firebase-tools@13.35.1

      - name: Show Firebase CLI version
        run: firebase --version

      - name: Deploy extracted files to Firebase Hosting
        run: |
          firebase deploy \
            --only hosting:cuba-zip-bundle-dev --project cuba-stage \
            --token "${{ secrets.FIREBASE_TOKEN }}" \
            --non-interactive 
