name: Push to firebase

on:
  push:
    branches:
      - Aneesh-mai
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Install Firebase CLI
        if: steps.extracted.outputs.count != '0'
        run: npm install -g firebase-tools@13.35.1

      - name: Show Firebase CLI version
        if: steps.extracted.outputs.count != '0'
        run: firebase --version

      - name: Deploy extracted files to Firebase Hosting
        if: steps.extracted.outputs.count != '0'
        run: |
          firebase deploy \
            --only hosting:{cuba-zip-bundle-dev --project cuba-stage} \
            --token "${{ secrets.FIREBASE_TOKEN }}" \
            --non-interactive 
